library minimalistic_bottom_navigation;

export 'package:minimalistic_bottom_navigation/src/minimalistic_bottom_bar.dart';
export 'package:minimalistic_bottom_navigation/src/minimalistic_bottom_bar_item.dart';